apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waiter
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
