apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: waiter
  apiGroup: rbac.authorization.k8s.io
