apiVersion: batch/v1
kind: Job
metadata:
  name: spark-mkdir
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-parent-dir
        image: zookage-util
        args:
        - wait-for-job
        - hdfs-mkdir
      containers:
      - name: mkdir
        image: zookage-util
        command:
        - /bin/bash
        args:
        - -c
        - |
          docker-entrypoint.sh hdfs-mkdir /user/spark spark:spark 755
          docker-entrypoint.sh hdfs-mkdir /user/spark/applicationHistory spark:spark 1777
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      restartPolicy: Never
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
