commonLabels:
  component: env
configMapGenerator:
- name: hadoop-env
  literals:
  - HADOOP_HOME=/opt/hadoop
  - HADOOP_CONF_DIR=/etc/hadoop/conf
  - HADOOP_LOG_DIR=/mnt/log
- name: httpfs-env
  literals:
  - HTTPFS_TEMP=/var/tmp/httpfs
  - HADOOP_LOG_DIR=/mnt/log
  # for Hadoop 2.x
  - HTTPFS_LOG=/mnt/log
  - HTTPFS_SILENT=false
  - HTTPFS_CONFIG=/etc/hadoop/conf
  - CATALINA_BASE=/var/opt/catalina/tomcat
- name: hive-env
  literals:
  - HIVE_HOME=/opt/hive
  - HIVE_CONF_DIR=/etc/hive/conf
  - HADOOP_OPTS=-Dderby.system.home=/tmp/derby
- name: spark-env
  literals:
  - SPARK_HOME=/opt/spark
  - SPARK_CONF_DIR=/etc/spark/conf
  - LD_LIBRARY_PATH=/opt/hadoop/lib/native
- name: tez-env
  literals:
  - TEZ_JARS=/opt/tez
  - TEZ_CONF_DIR=/etc/tez/conf
