apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-httpfs
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    spec:
      initContainers:
      - name: httpfs-cp-tomcat
        image: zookage-hadoop
        command:
        - /bin/bash
        args:
        - -c
        - '$(HADOOP_HOME)/bin/hdfs version | grep "Hadoop 2." && cp -R "$(HADOOP_HOME)/share/hadoop/httpfs/tomcat" "$(CATALINA_BASE)" || true'
        envFrom:
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: httpfs-env
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
      - name: httpfs-chown-tomcat
        image: zookage-hadoop
        command:
        - /bin/bash
        args:
        - -c
        - '$(HADOOP_HOME)/bin/hdfs version | grep "Hadoop 2." && chown -R httpfs:httpfs "$(CATALINA_BASE)" || true'
        envFrom:
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: httpfs-env
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
      containers:
      - name: httpfs
        image: zookage-hadoop
        command:
        - /bin/bash
        args:
        - -c
        - '$(HADOOP_HOME)/bin/hdfs version | grep "Hadoop 2." && "$(HADOOP_HOME)/sbin/httpfs.sh" run || "$(HADOOP_HOME)/bin/hdfs" httpfs'
        envFrom:
        - configMapRef:
            name: hadoop-env
        - configMapRef:
            name: httpfs-env
        readinessProbe:
          tcpSocket:
            port: 14000
        securityContext:
          runAsUser: 1014
          runAsGroup: 1014
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
        - name: mnt
          mountPath: /mnt
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
