apiVersion: batch/v1
kind: Job
metadata:
  name: hive-mkdir
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-parent-dir
        image: zookage-util
        args:
        - wait-for-job
        - hdfs-mkdir
      - name: mkdir-hive
        image: zookage-util
        args:
        - hdfs-mkdir
        - /user/hive
        - hive:hive
        - "751"
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      containers:
      - name: mkdir-warehouse
        image: zookage-util
        args:
        - hdfs-mkdir
        - /user/hive/warehouse
        - hive:hive
        - "1777"
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      restartPolicy: Never
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
