apiVersion: batch/v1
kind: Job
metadata:
  name: hdfs-mkdir
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-namenode
        image: zookage-util
        args:
        - wait-for-rollout
        - statefulset/hdfs-namenode
      containers:
      - name: mkdir-apps
        image: zookage-util
        args:
        - hdfs-mkdir
        - /apps
        - hdfs:supergroup
        - "755"
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      - name: mkdir-tmp
        image: zookage-util
        args:
        - hdfs-mkdir
        - /tmp
        - hdfs:supergroup
        - "1777"
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      - name: mkdir-user
        image: zookage-util
        args:
        - hdfs-mkdir
        - /user
        - hdfs:supergroup
        - "755"
        envFrom:
        - configMapRef:
            name: hadoop-env
        env:
        - name: HADOOP_USER_NAME
          value: hdfs
        volumeMounts:
        - name: hadoop-conf
          mountPath: /etc/hadoop/conf
      restartPolicy: Never
      volumes:
      - name: hadoop-conf
        configMap:
          name: hadoop-conf
      - name: mnt
        emptyDir: {}
