namespace: zookage
commonLabels:
  owner: zookage
bases:
- base/common
- base/hdfs
- base/yarn
- base/spark
- base/tez
- base/mapreduce
- base/hive
- base/client
images:
- name: zookage-hadoop
  newName: zookage/zookage-hadoop
  newTag: "3.1.4"
- name: zookage-hive
  newName: zookage/zookage-hive
  newTag: "3.1.2-guava-27.0-jre"
- name: zookage-spark
  newName: zookage/zookage-spark
  newTag: "3.0.1"
- name: zookage-tez
  newName: zookage/zookage-tez
  newTag: "0.9.2-guava-27.0-jre-jersey-1.19-servlet-api-3.1.0-without-jetty"
- name: zookage-util
  newName: zookage/zookage-util
  newTag: "0.1.0"
