namespace: zookage
commonLabels:
  owner: zookage
bases:
- base/common
- base/zookeeper
- base/hdfs
- base/yarn
- base/spark
- base/tez
- base/mapreduce
- base/hive
- base/client
images:
- name: zookage-hadoop
  newName: zookage/zookage-hadoop
  newTag: "test"
- name: zookage-hive
  newName: zookage/zookage-hive
  newTag: "test"
- name: zookage-spark
  newName: zookage/zookage-spark
  newTag: "3.0.1"
- name: zookage-tez
  newName: zookage/zookage-tez
  newTag: "test"
- name: zookage-zookeeper
  newName: zookage/zookage-zookeeper
  newTag: "3.6.2"
- name: zookage-util
  newName: zookage/zookage-util
  newTag: "test"
patchesStrategicMerge:
# Make HDFS highly available
# - patches/ha/hdfs.yaml
