namespace: zookage
commonLabels:
  owner: zookage
bases:
- base/common
# - base/zookeeper
- base/hdfs
# - base/hbase
- base/yarn
# - base/spark
- base/tez
# - base/mapreduce
- base/hive
- base/client
images:
- name: zookage-hadoop
  newName: zookage/zookage-hadoop
  newTag: "3.3.1-zookage-0.2"
- name: zookage-hbase
  newName: zookage/zookage-hbase
  newTag: "2.5.3-hadoop-3.3.1-zookage-0.2"
- name: zookage-hive
  newName: zookage/zookage-hive
  newTag: "4.0.0-alpha-2-zookage-0.2"
- name: zookage-spark
  newName: zookage/zookage-spark
  newTag: "3.1.1-zookage-0.2"
- name: zookage-tez
  newName: zookage/zookage-tez
  newTag: "0.10.2-zookage-0.2"
- name: zookage-zookeeper
  newName: zookage/zookage-zookeeper
  newTag: "3.6.2-zookage-0.2"
- name: zookage-util
  newName: zookage/zookage-util
  newTag: "0.2.1"
patches:
### High Availability ###
# - patches/ha/hdfs.yaml
# - patches/ha/yarn.yaml
