namespace: zookage
commonLabels:
  owner: zookage
bases:
- base/common
# - base/zookeeper
- base/hdfs
- base/yarn
- base/spark
- base/tez
- base/mapreduce
- base/hive
- base/client
images:
- name: zookage-hadoop
  newName: zookage/zookage-hadoop
  newTag: "3.2.2-zookage-0.2"
- name: zookage-hive
  newName: zookage/zookage-hive
  newTag: "3.1.2-guava-27.0-jre-zookage-0.2"
- name: zookage-spark
  newName: zookage/zookage-spark
  newTag: "3.0.1-zookage-0.2"
- name: zookage-tez
  newName: zookage/zookage-tez
  newTag: "0.9.2-guava-27.0-jre-jersey-1.19-servlet-api-3.1.0-without-jetty-zookage-0.2"
- name: zookage-zookeeper
  newName: zookage/zookage-zookeeper
  newTag: "3.6.2-zookage-0.2"
- name: zookage-util
  newName: zookage/zookage-util
  newTag: "0.2.0"
patchesStrategicMerge:
### High Availability ###
# - patches/ha/hdfs.yaml
# - patches/ha/yarn.yaml
