apiVersion: batch/v1
kind: Job
metadata:
  name: package-hbase
spec:
  template:
    spec:
      containers:
      - name: zookage-hbase
        image: zookage-hbase
        command:
        - /bin/bash
        args:
        - -c
        - "rm -rf /mnt/zookage/hbase-client && cp -R /opt/hbase-client /mnt/zookage/hbase-client"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: package-home
          mountPath: /mnt/zookage
      restartPolicy: Never
      volumes:
      - name: package-home
        hostPath:
          path: /opt/zookage
