apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookage-package-hbase-client
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/zookage/hbase-client
  storageClassName: zookage-package-hbase-client
