apiVersion: batch/v1
kind: Job
metadata:
  name: package-hive
spec:
  template:
    spec:
      containers:
      - name: zookage-hive
        image: zookage-hive
        command:
        - /bin/bash
        args:
        - -c
        - "rm -rf /mnt/zookage/hive && cp -R /opt/hive /mnt/zookage/hive && rm /mnt/zookage/hive/lib/log4j-slf4j-impl*"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: package-home
          mountPath: /mnt/zookage
      restartPolicy: Never
      volumes:
      - name: package-home
        hostPath:
          path: /opt/zookage
