apiVersion: batch/v1
kind: Job
metadata:
  name: package-zookeeper
spec:
  template:
    spec:
      containers:
      - name: zookage-zookeeper
        image: zookage-zookeeper
        command:
        - /bin/bash
        args:
        - -c
        - "rm -rf /mnt/zookage/zookeeper && cp -R /opt/zookeeper /mnt/zookage/zookeeper"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: package-home
          mountPath: /mnt/zookage
      restartPolicy: Never
      volumes:
      - name: package-home
        hostPath:
          path: /opt/zookage
